id: I7179F199
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T04:33:30+00:00'
last_modified: '2022-06-08T10:30:40.931011+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27216
  title: ཟིན་ཏིག་མཛེས་རྒྱན་བདུད་རྩི་སྨན་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    37BA:
      image_group_id: I1CZ1042
      title: ''
      total_pages: 196
      order: 1
      base_file: 37BA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
