id: P009367
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 19:35:28.922850
source_metadata:
  id: bdr:W27216
  title: ཟིན་ཏིག་མཛེས་རྒྱན་བདུད་རྩི་སྨན་མཛོད
  author: ''
  volumes:
    124f91cf8ace44f5b5d036667d55f97b:
      image_group_id: I1CZ1042
      title: ''
      volume_number: 1
      total_pages: 196
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
